### ISSUE TITLE
Suggestion: ReverseProxy

### ISSUE THREAD

**Issue by djzort** [ap/Plack-Middleware-RedirectSSL#5]
Not an issue, just a suggestion - you might want to "SEE ALSO" P::M::ReverseProxy - https://metacpan.org/pod/Plack::Middleware::ReverseProxy

As this layer will take care of interpreting headers of a http request thats actually https from the reverseproxy/loadbalancer

**Comment by ap** [comment]
Makes sense.

I was on the fence about it at first because “I don’t want to add links to every possibly related thing to the docs”. But I guess it’s worth pointing out that ReverseProxy needs to be in front of RedirectSSL in order for RedirectSSL to work in that situation.

**Comment by ap** [comment]
Just shipped 1.301 to CPAN, which includes this, along with other documentation fixes. Thank you for the suggestion. Share and enjoy 😊
